### ISSUE TITLE
香港的网站好像都打不开

### ISSUE THREAD

**Issue by kookob** [wspl/CIDR2PAC#2]
是pac列表里面没包含香港IP吗？按理香港也应该走代理，不知道为啥打不开？

**Comment by wspl** [comment]
没包含，按理说会走代理的。
不过这个 ip 列表一直都在更新，偶尔会有漏掉的 ip 段。那个打不开的 ip 能告诉我吗

**Comment by kookob** [comment]
我有用henghost.com（服务器在香港）这个服务商的产品，发现用pac之后。
henghost.com（IP：103.249.110.32）这个主站访问不了，而且我自己在香港建的站也是打不开。
103.249.110.*

我把上面域名和IP都加入白名单后，就可以了。
我默认代理返回是：'PROXY 127.0.0.1:1080; DIRECT';
按理说代理打不开，也应该直连，不知道是啥情况。

**Comment by kookob** [comment]
本身香港的站不管是直连或代理，用chrome扩展都是可以打开的。
不知道为什么用pac方式就是没反应。返回两者其中一个也应该是行的。

**Comment by wspl** [comment]
代码中并不包含能够匹配 103.249.110.\* 的 ip 段，按理说会走代理。而且pac只有走代理和直连两种情况……「打不开」显示的是什么错误呢？

**Comment by kookob** [comment]
502 Server dropped connection

The following error occurred while trying to access http://www.henghost.com/:

502 Server dropped connection

Generated Mon, 07 Sep 2015 05:13:35 GMT by Polipo on abc-PC:8123.

刷了很久，然后出现这上面错误。

**Comment by kookob** [comment]
你本地会吗？还是我本机问题？

**Comment by wspl** [comment]
我这边可以正常访问，最新版的 SS-CSharp，用 Privoxy 的版本
关闭全局代理 + Switchy Omega
